#spring.application.name=backend

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:9090/realms/realm-demo
          jwk-set-uri: http://localhost:9090/realms/realm-demo/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://localhost:3306/keycloack_db
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      generate-ddl: true
      ddl-auto: create
      show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      resource-id: demo
      principle-attribute: preferred_username